FROM fluentd:v1.8-1@sha256:610e4cd77b8f533d63b50e882ec044dd8ec729436f4ac7bbc6f8520f542c855f

# Use root account to use apk
USER root

# below RUN includes plugins - you may customize including plugins as you wish
RUN apk add --no-cache --update --virtual .build-deps \
        sudo build-base ruby-dev git \
 && sudo gem install fluent-plugin-papertrail \
 && sudo gem sources --clear-all \
 && apk del .build-deps \
 && rm -rf /tmp/* /var/tmp/* /usr/lib/ruby/gems/*/cache/*.gem

USER fluent
